/** Built-in reactive tool-view registry. Importing a module registers its view. */
import "./ask";
import "./ast-edit";
import "./ast-grep";
import "./autoresearch";
import "./bash";
import "./debug";
import "./default-renderer";
import "./edit";
import "./eval";
import "./fetch";
import "./github";
import "./glob";
import "./goal";
import "./grep";
import "./hub";
import "./lsp";
import "./mcp";
import "./memory";
import "./read";
import "./resolve";
import "./task";
import "./think";
import "./todo";
import "./vibe";
import "./web-search";
import "./write";
import "./xdev";

export * from "./model";
export * from "./output-notices";
export * from "./registry";
export * from "./view";
